[encoder]
base_dir = "/home/eagletmt/mnt/home/pt/heidemarie"
ffmpeg_args = [
  "-acodec", "aac", "-ac", "2", "-ar", "48000", "-ab", "128k",
  "-vcodec", "libx264", "-aspect", "16:9", "-filter:v", "yadif", "-s", "1280x720",
  "-crf", "21", "-b_strategy", "2", "-me_method", "umh", "-refs", "8", "-subq", "7", "-trellis", "2", "-deblock", "1:1",
  "-f", "mp4", "-map", "0", "-max_muxing_queue_size", "500",
]

[redis]
url = "redis://longarch.enospc.tv/1"

[sqs]
queue_url = "https://sqs.ap-northeast-1.amazonaws.com/274147449864/encode-jobs"
